const FUND_FOLDER_NAME = "lib2";
var fundSings = [
    { name: "FF1A - Pág. 50", text: "Vía libre"},
    { name: "FF2 - Pág. 50", text: "Vía libre condicional"},
    { name: "FF3A - Pág. 50", text: "Anuncio de precaución"},
    { name: "FF3B - Pág. 50", text: "Anuncio de precaución"},
    { name: "FF3C - Pág. 50", text: "Anuncio de precaución"},
    { name: "FF4 - Pág. 51", text: "Preanuncio de parada"},
    { name: "FF5A - Pág. 51", text: "Anuncio de parada"},
    { name: "FF5B - Pág. 51", text: "Anuncio de parada"},
    { name: "FF6 - Pág. 52", text: "Anuncio de parada inmediata"},
    { name: "FF7A - Pág. 52", text: "Parada"},
    { name: "FF7B - Pág. 52", text: "Parada"},
    { name: "FF7C - Pág. 53", text: "Parada selectiva"},
    { name: "FF7D - Pág. 53", text: "Parada selectiva"},
    { name: "FF8A - Pág. 54", text: "Rebase autorizado"},
    { name: "FF8B - Pág. 54", text: "Rebase autorizado"},
    { name: "FF8C - Pág. 54", text: "Rebase autorizado"},
    { name: "FF9 - Pág. 55", text: "Movimiento autorizado"},
    { name: "FF10A - Pág. 55", text: "Paso a nivel protegido"},
    { name: "FF10B - Pág. 55", text: "Paso a nivel protegido"},
    { name: "FF11A - Pág. 56", text: "Paso a nivel sin protección"},
]